name: CI Test

on:
  workflow_dispatch:
  push:
    paths:
      - pubspec.yaml
    tags: ["v*"]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: 'echo "$KEY_JKS_BASE64" | openssl base64 -d -out key.jks'
        shell: bash
        env:
          KEY_JKS_BASE64: ${{secrets.KEY_JKS_BASE64}}
      - run: 'echo "$KEY_PROPERTIES" > android/key.properties'
        shell: bash
        env:
          KEY_PROPERTIES: ${{secrets.KEY_PROPERTIES}}
      - run: flutter pub get
      - run: mkdir outputs
      - run: flutter build apk --target-platform android-arm
      - run: cp build/app/outputs/flutter-apk/app-release.apk outputs/android-arm.apk
      - run: flutter clean
      - run: flutter build apk --target-platform android-arm64
      - run: cp build/app/outputs/flutter-apk/app-release.apk outputs/android-arm64.apk
      - run: flutter clean
      - run: flutter build apk --target-platform android-x64
      - run: cp build/app/outputs/flutter-apk/app-release.apk outputs/android-x64.apk
      - run: flutter clean      
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: Release ${{ github.ref }}
#           draft: false
#           prerelease: false
      - run: |
          set -x
          assets=()
          for asset in ./outputs/*.apk; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
